#!/bin/sh

stow --verbose --target=/home/radian --dir=src/emacs   dotfiles
stow --verbose --target=/home/radian --dir=src/fish    dotfiles
stow --verbose --target=/home/radian --dir=src/firefox dotfiles
stow --verbose --target=/home/radian --dir=src/git     dotfiles
stow --verbose --target=/home/radian --dir=src/haskell dotfiles
stow --verbose --target=/home/radian --dir=src/mbsync  dotfiles
stow --verbose --target=/home/radian --dir=src/msmtp   dotfiles
stow --verbose --target=/home/radian --dir=src/mutt    dotfiles
stow --verbose --target=/home/radian --dir=src/urxvt   dotfiles
stow --verbose --target=/home/radian --dir=src/vim     dotfiles
stow --verbose --target=/home/radian --dir=src/xmonad  dotfiles
