#!/bin/sh

stow --verbose --target=/home/radian/bin --dir=src/haskell   bin
stow --verbose --target=/home/radian/bin --dir=src/utilities bin
stow --verbose --target=/home/radian/bin --dir=src/xmonad    bin
